apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-orchestrator
spec:
  template:
    spec:
      containers:
        - name: search-orchestrator
          image: us-central1-docker.pkg.dev/socioprophet-platform/socioprophet/search-orchestrator@sha256:dd342da260dc1d5953f4588f02aca319c2a357240c5b55d3ab3137b3e96a864b
          imagePullPolicy: IfNotPresent
