apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-orchestrator
spec:
  template:
    spec:
      containers:
        - name: search-orchestrator
          image: ghcr.io/socioprophet/prophet-platform/search-orchestrator@sha256:bbfea6e4a7ea432d77766a37464dfa666242dfe2621fc0e586ca2bde80c52066
          imagePullPolicy: IfNotPresent
