apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: workspace-minio-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 20Gi
