/**
 * synthesize — cited answer synthesis over the fanned search results (Perplexity parity, sovereign moat).
 *
 * The gateway fans web + the sovereign commons into a blended result set; this turns that into a
 * synthesized answer that cites its sources, generated by a SOVEREIGN LLM (an OpenAI-compatible endpoint
 * you host — never a vendor by default). The answer is grounded ONLY in the fanned results (each numbered
 * as a citation), so it can't hallucinate past what was retrieved — the opposite of an ungrounded chatbot.
 *
 * Opt-in + fail-open: no SEARCH_LLM_URL configured → we return the citations with no answer (the surface
 * degrades to plain results), and any LLM error does the same. Read-only; never throws into the request.
 */
import type { SearchResult } from './gateway.js'

export interface Citation { n: number; title: string; url: string; source: string }
export interface SynthesisResult {
  answer: string
  citations: Citation[]
  synthesized: boolean // false when no LLM is configured or the call failed → surface shows results only
}

interface LlmConfig { url: string; model: string; key: string }

function llmConfig(): LlmConfig | null {
  const url = (process.env['SEARCH_LLM_URL'] ?? '').replace(/\/$/, '')
  const model = process.env['SEARCH_LLM_MODEL'] ?? ''
  if (!url || !model) return null // sovereign LLM not configured → synthesis off (results-only)
  return { url, model, key: process.env['SEARCH_LLM_KEY'] ?? '' }
}

export function synthesisEnabled(): boolean { return llmConfig() !== null }

const MAX_SOURCES = 8

/** Synthesize a cited answer from the fanned results using the configured sovereign LLM. */
export async function synthesize(query: string, results: SearchResult[], fetchImpl: typeof fetch = fetch): Promise<SynthesisResult> {
  const top = results.slice(0, MAX_SOURCES)
  const citations: Citation[] = top.map((r, i) => ({ n: i + 1, title: r.title, url: r.url, source: r.source }))
  const cfg = llmConfig()
  if (!cfg || top.length === 0) return { answer: '', citations, synthesized: false }

  const sources = top.map((r, i) => `[${i + 1}] ${r.title} (${r.source})\n${r.snippet}\n${r.url}`).join('\n\n')
  const prompt =
    `You are a sovereign research assistant. Answer the question using ONLY the numbered sources below. ` +
    `Cite every claim inline as [n]. If the sources do not answer it, say so plainly — do not use outside knowledge.\n\n` +
    `Question: ${query}\n\nSources:\n${sources}\n\nAnswer (with [n] citations):`

  try {
    const headers: Record<string, string> = { 'content-type': 'application/json' }
    if (cfg.key) headers['authorization'] = `Bearer ${cfg.key}`
    const res = await fetchImpl(`${cfg.url}/chat/completions`, {
      method: 'POST', headers,
      body: JSON.stringify({ model: cfg.model, temperature: 0.2, max_tokens: 600, messages: [{ role: 'user', content: prompt }] }),
      signal: AbortSignal.timeout(30_000),
    })
    if (!res.ok) return { answer: '', citations, synthesized: false }
    const data = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> }
    const answer = data.choices?.[0]?.message?.content?.trim() ?? ''
    return { answer, citations, synthesized: answer.length > 0 }
  } catch {
    return { answer: '', citations, synthesized: false }
  }
}
