apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prophet-platform
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount-rbac.yaml
  - pvc.yaml
  - networkpolicy.yaml
