// The FIXTURE COHORT the residual surrogate is fitted on.
//
// 🔴 SYNTHETIC. Every subject here is generated, not real. There is no real patient data in this repo
// and none is used to fit anything. Read the honesty note at the bottom of this file before quoting any
// number that comes out of it.
//
// The cohort exists to answer one question honestly: does a learned RESIDUAL on top of the mechanistic
// model actually reduce error, or is it decoration? To make that question answerable the cohort's
// ground truth is generated by a RICHER process than the mechanistic model can express — the same
// compartment structure, but with per-subject modifiers that the population-parameter model does not
// consume. That is exactly the real-world situation: the ODE knows dose and age; it does not know that
// this person takes 6 doses in 10, has low plasma renin, or is spilling albumin.
//
// The four modifiers are all REAL, ROUTINELY OBSERVED clinical covariates, chosen so the residual is
// something a clinic could actually supply:
//   • adherencePdc  — proportion of days covered, straight off pharmacy refill data.
//   • reninIndex    — plasma-renin-activity band. Low-renin patients respond less to ACE inhibition;
//                     this is the classic responder / non-responder axis for RAS blockade.
//   • bmi           — modulates the glycaemic response to a lifestyle + metformin regimen.
//   • uacr          — urine albumin-to-creatinine ratio (LOINC 9318-7), the standard predictor of the
//                     RATE of eGFR decline, and something an age+BP model is blind to.
//
// Determinism: a seeded linear-congruential generator, never Math.random(), so the cohort, the fit and
// therefore the seal are bit-reproducible across runs and machines.
import { simulate, anchorTo, DEFAULT_PARAMS, type MechanisticParams, type Compartment } from './mechanistic.js';

export const COHORT_ID = 'synthetic-cardiometabolic-cohort';
export const COHORT_VERSION = 'v1';
export const HORIZON_DAYS = 90;
export const SAMPLE_DAYS = [15, 30, 45, 60, 75, 90];

/** Deterministic uniform stream (LCG, glibc constants). Never Math.random. */
function lcg(seed: number) {
  let s = seed >>> 0;
  return () => { s = (1103515245 * s + 12345) >>> 0; return s / 4294967296; };
}
/** Box–Muller from the same deterministic stream — measurement noise that is reproducible. */
function gauss(rand: () => number): number {
  const u = Math.max(rand(), 1e-12), v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

export interface CohortSubject {
  id: string;
  /** Observable covariates — what a clinic has and the mechanistic model does not consume. */
  covariates: { adherencePdc: number; reninIndex: number; bmi: number; uacr: number };
  /** The subject's day-0 recorded observations (what the twin is anchored to). */
  baseline: { sbp: number; a1c: number; egfr: number };
  /** The generated "what actually happened" trajectory, per compartment, at SAMPLE_DAYS. */
  truth: Record<Compartment, number[]>;
  split: 'train' | 'test';
}

/**
 * Ground truth: the SAME compartment model, run with subject-specific parameters that the population
 * model does not have, plus measurement noise. Nothing here is fitted — this is the generator.
 */
function truthParams(base: MechanisticParams, cv: CohortSubject['covariates']): MechanisticParams {
  return {
    cardio: {
      ...base.cardio,
      // missed doses reduce the average mass administered; low renin reduces the achievable effect
      doseMg: base.cardio.doseMg * cv.adherencePdc,
      Emax: base.cardio.Emax * (0.55 + 0.5 * cv.reninIndex),
    },
    hepatic: {
      ...base.hepatic,
      // a heavier subject's regimen drives mean glucose to a higher floor
      mgTarget: base.hepatic.mgTarget + (cv.bmi - 27) * 1.9,
    },
    renal: {
      ...base.renal,
      // albuminuria accelerates nephron loss on top of age and pressure
      agePerYear: base.renal.agePerYear + 1.6 * cv.uacr,
      bpSensitivity: base.renal.bpSensitivity * (1 + 0.8 * cv.uacr),
    },
  };
}

/** Measurement noise, 1-σ per compartment, in observable units (assay + biological day-to-day variation). */
const NOISE: Record<Compartment, number> = { cardio: 3.0, hepatic: 0.12, renal: 1.6 };

/** Build the cohort. Deterministic for a given seed. */
export function buildCohort(n = 60, seed = 20260729): CohortSubject[] {
  const rand = lcg(seed);
  const subjects: CohortSubject[] = [];
  for (let i = 0; i < n; i++) {
    const covariates = {
      adherencePdc: 0.45 + 0.55 * rand(),   // 45–100% of days covered
      reninIndex: rand(),                    // 0 = low renin (poor responder) … 1 = high renin
      bmi: 23 + 12 * rand(),                 // 23–35
      uacr: rand() ** 1.6,                   // 0–1 normalised albuminuria, right-skewed like the real thing
    };
    const baseline = {
      sbp: 130 + 18 * rand(),
      a1c: 5.4 + 1.4 * rand(),
      egfr: 70 + 40 * rand(),
    };
    const base = anchorTo(baseline, DEFAULT_PARAMS);
    const run = simulate(HORIZON_DAYS, truthParams(base, covariates));
    const truth: Record<Compartment, number[]> = { cardio: [], hepatic: [], renal: [] };
    for (const d of SAMPLE_DAYS) {
      const s = run.steps[d]!;
      truth.cardio.push(s.sbp + NOISE.cardio * gauss(rand));
      truth.hepatic.push(s.a1c + NOISE.hepatic * gauss(rand));
      truth.renal.push(s.egfr + NOISE.renal * gauss(rand));
    }
    subjects.push({ id: `synth-${String(i).padStart(3, '0')}`, covariates, baseline, truth, split: i < Math.floor(n * 0.67) ? 'train' : 'test' });
  }
  return subjects;
}

/** The mechanistic-only prediction for a subject — population parameters, full adherence assumed.
 *  Memoised per subject: the fit reads it once per organ and the integration is the expensive part. */
const MECH_CACHE = new WeakMap<CohortSubject, Record<Compartment, number[]>>();
export function mechanisticFor(s: CohortSubject): Record<Compartment, number[]> {
  const hit = MECH_CACHE.get(s);
  if (hit) return hit;
  const run = simulate(HORIZON_DAYS, anchorTo(s.baseline, DEFAULT_PARAMS));
  const out = {
    cardio: SAMPLE_DAYS.map((d) => run.steps[d]!.sbp),
    hepatic: SAMPLE_DAYS.map((d) => run.steps[d]!.a1c),
    renal: SAMPLE_DAYS.map((d) => run.steps[d]!.egfr),
  };
  MECH_CACHE.set(s, out);
  return out;
}

// ── HONESTY NOTE — read this before quoting a fit number ──────────────────────────────────────────
//
// The cohort is synthetic and its ground truth is generated by a superset of the mechanistic model.
// So "the residual improves fit here" demonstrates that the RESIDUAL MACHINERY WORKS and that the
// covariates carry learnable signal the ODE does not consume. It is NOT evidence that this surrogate
// would improve fit on real patients, and it must never be reported as clinical validation. The
// measured number is reported on HELD-OUT SUBJECTS (never fitted on) with measurement noise present,
// which is the strongest claim this construction can honestly support — and that claim is about the
// pipeline, not about medicine.
