apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: osm-map-api
  app.kubernetes.io/part-of: prophet-platform
