apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: socioprophet
commonLabels:
  app: zot
  app.kubernetes.io/part-of: sovereign-registry
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
