apiVersion: apps/v1
kind: Deployment
metadata:
  name: socioprophet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socioprophet-api
  template:
    metadata:
      labels:
        app: socioprophet-api
    spec:
      containers:
        - name: api
          image: ghcr.io/SocioProphet/socioprophet-api:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: TRITRPC_LISTEN_ADDR
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: TRITRPC_LISTEN_ADDR
            - name: TRITRPC_ALLOW_INSECURE_DEV_KEY
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: TRITRPC_ALLOW_INSECURE_DEV_KEY
            - name: TRITRPC_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: tritrpc-shared-key
                  key: TRITRPC_KEY_HEX
                  optional: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          ports:
            - containerPort: 9000
              name: tritrpc
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 2
            periodSeconds: 5
