apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: api-config
    literals:
      - TRITRPC_LISTEN_ADDR=tcp://0.0.0.0:9000
      - TRITRPC_ALLOW_INSECURE_DEV_KEY=0
