// routing.ts — turn triage into ACTION (the Zocdoc pattern, verbs 5 Route + 7 Prepare). Given a
// triage result it recommends the care SETTING, a candidate SPECIALTY, the visit MODALITY
// (telehealth vs in-person), a timing window, and a clinician-facing PRE-VISIT SUMMARY so the visit
// starts with context instead of repetition. Non-diagnostic: it routes the level and kind of care;
// it does not diagnose. Matching on insurance/availability is the booking layer (verb 6, later).
import { directory } from './providers.js';
import type { TriageResult, Urgency } from './triage.js';

export type CareSetting = 'self-care' | 'telehealth' | 'primary-care' | 'urgent-care' | 'emergency-department';
export type Modality = 'self-care' | 'telehealth' | 'in-person';

const SETTING: Record<Urgency, CareSetting> = {
  emergency: 'emergency-department',
  urgent: 'urgent-care',
  routine: 'primary-care',
  monitor: 'self-care',
  'self-care': 'self-care',
};
const TIMING: Record<Urgency, string> = {
  emergency: 'now',
  urgent: 'within a few hours',
  routine: 'within a few days',
  monitor: 'no visit needed unless it changes',
  'self-care': 'no visit needed unless it changes',
};
const MODALITY: Record<CareSetting, Modality> = {
  'emergency-department': 'in-person',
  'urgent-care': 'in-person',
  'primary-care': 'telehealth',    // routine can often start virtual
  telehealth: 'telehealth',
  'self-care': 'self-care',
};

// Map a red-flag id / finding cluster to a candidate specialty. Coarse + safety-first; a router,
// not a diagnosis. Unknown → the safe default of primary care / emergency medicine by urgency.
const SPECIALTY_BY_FLAG: Record<string, string> = {
  cardiac: 'Cardiology / Emergency Medicine',
  stroke: 'Neurology / Emergency Medicine',
  airway: 'Emergency Medicine',
  anaphylaxis: 'Emergency Medicine / Allergy',
  hemorrhage: 'Emergency Medicine',
  neuro: 'Neurology / Emergency Medicine',
  sepsis: 'Emergency Medicine',
  'mental-health': 'Psychiatry / Crisis Services',
  obstetric: 'Obstetrics / Emergency Medicine',
  neurovascular: 'Vascular Surgery / Emergency Medicine',
};
const SPECIALTY_HINTS: { any: string[]; specialty: string }[] = [
  { any: ['rash', 'skin', 'lesion', 'acne', 'eczema', 'wound', 'cut', 'burn', 'bite'], specialty: 'Dermatology / Primary Care' },
  { any: ['knee', 'ankle', 'sprain', 'joint', 'back pain', 'shoulder', 'fracture'], specialty: 'Orthopedics / Primary Care' },
  { any: ['cough', 'sore throat', 'congestion', 'sinus', 'fever'], specialty: 'Primary Care' },
  { any: ['anxiety', 'depression', 'mood', 'sleep'], specialty: 'Behavioral Health / Primary Care' },
  { any: ['blood pressure', 'cholesterol', 'diabetes', 'a1c'], specialty: 'Primary Care / Internal Medicine' },
];

function suggestSpecialty(t: TriageResult): string {
  if (t.redFlags.length) return SPECIALTY_BY_FLAG[t.redFlags[0]!.id] ?? 'Emergency Medicine';
  const blob = [t.complaint, ...t.perceived].join(' ').toLowerCase();
  for (const h of SPECIALTY_HINTS) if (h.any.some((k) => blob.includes(k))) return h.specialty;
  return 'Primary Care';
}

export interface CareRoute {
  urgency: Urgency;
  setting: CareSetting;
  modality: Modality;
  timing: string;
  specialty: string;
  action: string;                 // the plain-language "go here, now/soon" line
  candidateProviders: { id: string; name: string; specialty: string; org: string; location: string; verified: boolean; telehealth?: boolean }[];
  preVisitSummary: string;        // the clinician-facing handoff (verb 7 Prepare)
  disclaimer: string;
}

// A structured, de-identified-by-default pre-visit summary the person can carry into the visit.
function preVisitSummary(t: TriageResult, specialty: string): string {
  const flags = t.redFlags.length ? `Danger signs noted: ${t.redFlags.map((r) => r.reason).join('; ')}.` : 'No emergency danger signs noted at intake.';
  const findings = t.perceived.length ? t.perceived.join(', ') : (t.complaint || 'symptoms described in free text');
  return [
    `PRE-VISIT SUMMARY (patient-generated, non-diagnostic; a clinician confirms)`,
    `Chief concern: ${t.complaint || '(free-text intake)'}`,
    `Structured findings: ${findings}`,
    `Triage urgency: ${t.urgency}. Suggested setting: ${SETTING[t.urgency]}. ${flags}`,
    `Suggested specialty: ${specialty}.`,
    t.evidence ? `Reference context: ${t.evidence.slice(0, 240)}` : `Reference context: none retrieved.`,
    `Generated by SocioProphet triage — informational; not a diagnosis.`,
  ].join('\n');
}

export function route(t: TriageResult): CareRoute {
  const setting = SETTING[t.urgency];
  const specialty = suggestSpecialty(t);
  // Candidate providers: only surfaced when a real visit is warranted (never for self-care/monitor).
  const wantsVisit = t.urgency === 'routine' || t.urgency === 'urgent' || t.urgency === 'emergency';
  const spKey = specialty.split(/[\/ ]/)[0]!.toLowerCase();
  const candidateProviders = wantsVisit
    ? directory()
        .filter((p) => setting !== 'emergency-department' ? p.specialty.toLowerCase().includes(spKey) || p.specialty.toLowerCase().includes('primary') : true)
        .slice(0, 3)
        .map((p) => ({ id: p.id, name: p.name, specialty: p.specialty, org: p.org, location: p.location, verified: p.verified }))
    : [];

  const action = t.urgency === 'emergency'
    ? `Go to the ${setting.replace(/-/g, ' ')} ${TIMING[t.urgency]}.`
    : wantsVisit
      ? `See ${specialty} via ${MODALITY[setting].replace(/-/g, ' ')} ${TIMING[t.urgency]}.`
      : `${TIMING[t.urgency]}.`;

  return {
    urgency: t.urgency, setting, modality: MODALITY[setting], timing: TIMING[t.urgency],
    specialty, action, candidateProviders,
    preVisitSummary: preVisitSummary(t, specialty),
    disclaimer: 'Care routing is informational and non-diagnostic. Insurance, availability, and final suitability are confirmed at booking and by the clinician.',
  };
}
