# DNS module — generate the COMPLETE zone record set for the workspace plane from one source of truth,
# so a rollout is `tofu apply` + paste (or, once a provider token is wired, fully automated) — not a
# hand-typed runbook of a thousand cuts. Swap local_file for a provider (cloudflare/route53/google_dns/
# namecheap) resource and the same locals drive live records.

locals {
  fqdn = var.subdomain_prefix != "" ? "${var.subdomain_prefix}.${var.zone_name}" : var.zone_name

  # Service FQDNs
  mail   = "mail.${local.fqdn}"   # SMTP + MX target
  imap   = "imap.${local.fqdn}"   # IMAPS
  caldav = "caldav.${local.fqdn}" # Radicale (HTTP ingress)
  minio  = "storage.${local.fqdn}"
  argocd = "argocd.${local.fqdn}"

  imap_ip   = var.imap_ip != "" ? var.imap_ip : var.smtp_ip
  dmarc_rua = var.dmarc_rua != "" ? var.dmarc_rua : "postmaster@${var.zone_name}"
  spf_all   = var.spf_hardfail ? "-all" : "~all"
  have_mail = var.smtp_ip != ""
}

resource "local_file" "dns_records" {
  filename = "${path.root}/dns-records.txt"
  content  = <<-TXT
    # DNS records for ${var.zone_name} — GENERATED by infra/terraform/modules/dns. Do not hand-edit; change the vars.
    # HTTP(S) control-plane IP: ${var.control_plane_ip}

    ${local.caldav}  A  ${var.control_plane_ip}
    ${local.minio}   A  ${var.control_plane_ip}
    ${local.argocd}  A  ${var.control_plane_ip}
    %{if local.have_mail~}

    # --- Mail plane (keep the existing Google MX in place until mail-tester >= 9/10, THEN cut over) ---
    ${local.mail}  A    ${var.smtp_ip}
    ${local.imap}  A    ${local.imap_ip}
    ${var.zone_name}  MX   10 ${local.mail}.
    ${var.zone_name}  TXT  "v=spf1 ip4:${var.smtp_ip} ${local.spf_all}"
    _dmarc.${var.zone_name}  TXT  "v=DMARC1; p=${var.dmarc_policy}; rua=mailto:${local.dmarc_rua}; adkim=s; aspf=s"
    %{if var.dkim_public_key != ""~}
    ${var.dkim_selector}._domainkey.${var.zone_name}  TXT  "v=DKIM1; k=rsa; p=${var.dkim_public_key}"
    %{else~}
    # DKIM: set dkim_public_key to emit ${var.dkim_selector}._domainkey.${var.zone_name}
    %{endif~}

    # PTR / reverse-DNS (set on the SMTP IP at the cloud provider — NOT the authoritative zone):
    #   ${var.smtp_ip}  PTR  ${local.mail}
    # Verify:  dig -x ${var.smtp_ip} +short   ->   ${local.mail}.

    # Client autoconfig (SRV) — zero-touch mailbox setup, better than manual IMAP/SMTP entry:
    _imaps._tcp.${local.fqdn}       SRV 0 1 993 ${local.imap}.
    _submission._tcp.${local.fqdn}  SRV 0 1 587 ${local.mail}.
    _caldavs._tcp.${local.fqdn}     SRV 0 1 443 ${local.caldav}.
    _carddavs._tcp.${local.fqdn}    SRV 0 1 443 ${local.caldav}.
    %{else~}

    # Mail records omitted (smtp_ip not set — provision the SMTP LoadBalancer first).
    %{endif~}
  TXT
}
