apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy.yaml
  - configmap.yaml
  - deployment.yaml
  - deployment-smtp.yaml
  - service.yaml
  - pvc.yaml
  - backup-cronjob.yaml
namespace: socioprophet
