apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-mail-pvc
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
