apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/SocioProphet/socioprophet-api
    newName: ghcr.io/SocioProphet/socioprophet-api
    newTag: dev
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - TRITRPC_ALLOW_INSECURE_DEV_KEY=1
