apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: workspace-mail
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.socioprophet.ai/workspace-mail:sha-8f1bb2f5d6d4d9577113887bbfb79ce8305782b3
  - target:
      kind: PersistentVolumeClaim
      name: workspace-mail-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
