#!/usr/bin/env python3
"""Promote a frozen release-train digest into a wave overlay's image-patch — the
promote-MANY half of build-once-promote-many. NO build happens here: the digest is read
from the frozen manifest and written, unchanged, into the target wave's kustomize
image-patch. Running this for dev, then canary, then prod writes the IDENTICAL sha256 to
each wave overlay (INV-DEP-2 — promote-many, never rebuild).

The rendered patch pins by ``<image>@sha256:<digest>`` (INV-DEP-1). imagePullPolicy is
forced to ``IfNotPresent`` deliberately: a digest reference is already immutable, so
IfNotPresent is correct and cache-friendly — the estate's ":latest + IfNotPresent never
rolls" trap only bites *moving tags*, which this refuses to emit.

Usage
-----
  apply_wave_promotion.py \\
      --manifest releases/manifests/release-train.2026-08-02.manifest.json \\
      --component search-orchestrator \\
      --deployment search-orchestrator \\
      --container  search-orchestrator \\
      --kind Deployment \\
      --output infra/k8s/search-orchestrator/overlays/promote/canary/image-patch.yaml
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


def find_component(manifest: dict, component: str) -> dict:
    for c in manifest.get("components", []):
        if component in (c.get("id"), Path(c.get("image", "")).name, c.get("component")):
            return c
    raise SystemExit(f"::error::component {component!r} not present in frozen manifest "
                     f"{manifest.get('manifest_id')}")


def render_patch(kind: str, name: str, container: str, pinned_ref: str) -> str:
    # A Deployment lives in apps/v1; an Argo Rollouts Rollout is a CRD in argoproj.io/v1alpha1.
    # A strategic-merge patch must carry the target's real apiVersion or kustomize finds no match.
    api_version = "argoproj.io/v1alpha1" if kind == "Rollout" else "apps/v1"
    return (
        "# GENERATED by tools/apply_wave_promotion.py from the frozen release-train manifest.\n"
        "# Do not hand-edit the image line — re-run the promotion to change the pinned digest.\n"
        f"apiVersion: {api_version}\n"
        f"kind: {kind}\n"
        f"metadata:\n"
        f"  name: {name}\n"
        f"spec:\n"
        f"  template:\n"
        f"    spec:\n"
        f"      containers:\n"
        f"        - name: {container}\n"
        f"          image: {pinned_ref}\n"
        f"          imagePullPolicy: IfNotPresent\n"
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--manifest", type=Path, required=True)
    p.add_argument("--component", required=True)
    p.add_argument("--deployment", required=True, help="metadata.name of the workload to patch")
    p.add_argument("--container", required=True, help="container name to re-image")
    p.add_argument("--kind", default="Deployment", choices=["Deployment", "Rollout"])
    p.add_argument("--output", type=Path, required=True)
    args = p.parse_args(argv)

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    comp = find_component(manifest, args.component)
    digest = str(comp.get("digest", ""))
    pinned_ref = str(comp.get("pinned_ref", ""))
    if not DIGEST_RE.match(digest) or "@sha256:" not in pinned_ref:
        raise SystemExit(f"::error::frozen component {args.component} is not digest-pinned "
                         f"(digest={digest!r}, pinned_ref={pinned_ref!r}) — INV-DEP-1")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_patch(args.kind, args.deployment, args.container, pinned_ref),
                           encoding="utf-8")
    print(f"promoted {args.component} -> {pinned_ref} into {args.output} (no rebuild)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
