#!/usr/bin/env python3
"""No-drift gate for scripts a CronJob mounts via a ConfigMap.

An in-cluster CronJob mounts its script from a ConfigMap generated by kustomize. Kustomize's
default load-restrictor forbids a base from reading files outside its own directory, so the
canonical tool under tools/ must be COPIED into the kustomize base. Two copies of a script is
exactly the declared-not-enforced trap: the base copy silently drifts from the tested tools/
original, and the cluster runs stale code while CI proves the fresh one.

This gate makes the copy accountable: each (canonical, mirror) pair must be byte-identical, or
the build fails. It is the CronJob-script analogue of the vendored-engine and external-fixture
mirror gates already in this repo.

Self-excluding: this validator is not itself a mirror, so it is never in its own registry.

  verify_cronjob_script_mirrors.py            # check every registered pair
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (canonical source of truth, mirror the CronJob's ConfigMap is generated from).
MIRRORS: list[tuple[str, str]] = [
    ("tools/deploy_health_alert.py",
     "infra/k8s/deploy-health-alerter/base/deploy_health_alert.py"),
]


def main() -> int:
    problems: list[str] = []
    for canonical, mirror in MIRRORS:
        cpath, mpath = ROOT / canonical, ROOT / mirror
        if not cpath.is_file():
            problems.append(f"canonical missing: {canonical}")
            continue
        if not mpath.is_file():
            problems.append(f"mirror missing: {mirror} (copy {canonical} into the kustomize base)")
            continue
        if cpath.read_bytes() != mpath.read_bytes():
            problems.append(
                f"DRIFT: {mirror} != {canonical} — re-copy: cp {canonical} {mirror}")
    if problems:
        print(f"FAIL: {len(problems)} CronJob-script mirror problem(s):")
        for p in problems:
            print(f"  {p}")
        return 1
    print(f"OK: {len(MIRRORS)} CronJob-script mirror(s) byte-identical to their canonical source")
    return 0


if __name__ == "__main__":
    sys.exit(main())
