-- GENERATED by tools/gen_intelligence_superiority_seed.py -- do not edit by hand.
-- Persists the intelligence-superiority metric DEFINITIONS (Postgres).
insert into metric_definitions (
  metric_definition_id, name, family, regime, unit, direction, value_type, normalizer
) values
  ('mmlu_stem_accuracy', 'MMLU-STEM accuracy', 'task_performance', 'CWA_BINARY', 'fraction_correct', 'higher_better', 'scalar', 'bounded_0_1'),
  ('gpqa_diamond_accuracy', 'GPQA-Diamond accuracy', 'task_performance', 'CWA_BINARY', 'fraction_correct', 'higher_better', 'scalar', 'bounded_0_1'),
  ('swebench_verified_resolved', 'SWE-bench Verified resolved', 'agent_execution', 'CWA_BINARY', 'fraction_resolved', 'higher_better', 'scalar', 'bounded_0_1'),
  ('frontiermath_tier4_accuracy', 'FrontierMath Tier-4 accuracy', 'task_performance', 'CWA_BINARY', 'fraction_correct', 'higher_better', 'scalar', 'bounded_0_1'),
  ('arc_agi2_accuracy', 'ARC-AGI-2 accuracy', 'ontology_logic', 'CWA_BINARY', 'fraction_correct', 'higher_better', 'scalar', 'bounded_0_1'),
  ('kg_triple_plausibility', 'KG-BERT triple-plausibility held-out accuracy', 'grounding_factuality', 'CWA_BINARY', 'fraction_correct', 'higher_better', 'scalar', 'bounded_0_1');
