apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshell-fog-stack-standard
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/SocioProphet/prophet-platform
    targetRevision: main
    path: infra/argocd/cloudshell-fog-stack-standard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
