apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# p1-single-site: bump the metadata-cache PVC for a larger image estate.
bases:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: zot-cache
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 20Gi
